export const navLinks = [
    {
        title: "Home",
        href: "/home",
    },
    {
        title: "Movies",
        href: "/movies",
    },
    {
        title: "TV shows",
        href: "/tv shows",
    },
    {
        title: "Documentaries",
        href: "/documentaries",
    }
    ,
    {
        title: "Anime",
        href: "/anime",
    }
]

export const imageSets = [
    {
        imageUrl: 'https://fzmovies.host/imdb_images/The%20Cabin%20in%20the%20Woods.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/The.Maze.Runner.2014.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/Captain%20America%20The%20First%20Avenger.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/Blended.2014.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/Oldboy.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/Clash%20of%20the%20Titans.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/The%20Time%20Travelers%20Wife.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/Creed.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/Captain.America.The.Winter.Soldier.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/Need.For.Speed..2014.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/Hours.jpg',
    },
    {
        imageUrl: 'https://fzmovies.host/imdb_images/I.Am.Bolt.(2016).jpg',
    },
];


export const movies = [
    {
        title: "Aquaman and the Lost Kingdom",
        link: "https://www.imdb.com/title/tt9663764/?ref_=adv_li_tt",
        desc: "Arthur must enlist the help of his half-brother Orm in order to protect Atlantis against Black Manta, who has unleashed a devastating weapon in his obsessive quest to avenge his father's death.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ02sQRmJegl3scFQqVoixesTfjADdGtdw7TkIQF9JuPuwZLW_w",
        releaseDate: "2023",
        genre: "Adventure, Fantasy",
    },
    {
        title: "Jawan",
        link: "https://www.imdb.com/title/tt15354916/?ref_=adv_li_tt",
        desc: "A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.",
        ratings: "7.7",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQgq-Z09w3VchpLc9LVhG_R6vNnhgeaPX7pcouxWXUAELFWdPkp",
        releaseDate: "2023",
        genre: "Action, Thriller",
    },
    {
        title: "The Equalizer 3",
        link: "https://www.imdb.com/title/tt17024450/?ref_=adv_li_tt",
        desc: "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
        ratings: "7.1",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSSbIxdut987G-06iwjyGTtg6GQhafM-nG-Gtyc-9GMdrzPI9Ft",
        releaseDate: "2023",
        genre: "Action, Crime, Thriller",
    },
    {
        title: "Indiana Jones and the Dial of Destiny",
        link: "https://www.imdb.com/title/tt1462764/?ref_=adv_li_tt",
        desc: "Archaeologist Indiana Jones races against time to retrieve a legendary artifact that can change the course of history.",
        ratings: "6.7",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSAfbQzvGKy0oUKX3tKXOKirveHpqNU8fUxWNq6ghdDDLxeYxfw",
        releaseDate: "2023",
        genre: "Action, Adventure, Sci-Fi",

    },
    {
        title: "Teenage Mutant Ninja Turtles: Mutant Mayhem",
        link: "https://www.imdb.com/title/tt8589698/?ref_=adv_li_tt",
        desc: "The film follows the Turtle brothers as they work to earn the love of New York City while facing down an army of mutants.",
        ratings: "7.3",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR6fZCqFuwnsu7kHCgO_R3kHzzXrQr3_Vho8vsIR6EmeuaFi2ZY",
        releaseDate: "2023",
        genre: "Animation, Action, Adventure",
    },
    {
        title: "Spider-Man: Across the Spider-Verse",
        link: "https://www.imdb.com/title/tt9362722/?ref_=adv_li_tt",
        desc: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles must redefine what it means to be a hero.",
        ratings: "8.7",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQFHMCMi3SM6HVf0M-Ua0zLlXgBvdsyTT8JL47mVS58uxEaEPse",
        releaseDate: "2023",
        genre: "Animation, Action, Adventure",
    },
    {
        title: "The Flash",
        link: "https://www.imdb.com/title/tt0439572/?ref_=adv_li_tt",
        desc: "Barry Allen uses his super speed to change the past, but his attempt to save his family creates a world without super heroes, forcing him to race for his life in order to save the future.",
        ratings: "6.8",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQqLYH_Sfv0dDGSzu6UhTmaYUo1OxBSTtUmRjZIqazHipy3K6Al",
        releaseDate: "2023",
        genre: "Action, Adventure, Fantasy",
    },
    {
        title: "Expend4bles",
        link: "https://www.imdb.com/title/tt3291150/?ref_=adv_li_tt",
        desc: "Armed with every weapon they can get their hands on, the Expendables are the world's last line of defense and the team that gets called when all other options are off the table.",
        ratings: "5.0",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ5PZTuvkysbhL2DSfDdyF99K9DuHbczj6xICF-0MVLtNHBJ89i",
        releaseDate: "2023",
        genre: "Action, Adventure, Thriller",
    },
    {
        title: "Sound of Freedom",
        link: "https://www.imdb.com/title/tt7599146/?ref_=adv_li_tt",
        desc: "The incredible true story of a former government agent turned vigilante who embarks on a dangerous mission to rescue hundreds of children from sex traffickers.",
        ratings: "7.8",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWSxEMxvpI7ZvaK97TT-gqME2nPYtdHhlDBO4hEB-KnUshq-Qr",
        releaseDate: "2023",
        genre: "Action, Biography, Crime",
    },
    {
        title: "The Creator",
        link: "https://www.imdb.com/title/tt11858890/?ref_=adv_li_tt",
        desc: "Against the backdrop of a war between humans and robots with artificial intelligence, a former soldier finds the secret weapon, a robot in the form of a young child.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTUIJZiEThsXozTY2jFF1R9UQpLW3cWILFpMdbTLSwRdxGFnJro",
        releaseDate: "2023",
        genre: "Action, Adventure, Drama",
    },
    {
        title: "Guardians of the Galaxy Vol. 3 ",
        link: "https://www.imdb.com/title/tt6791350/?ref_=adv_li_tt",
        desc: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.",
        ratings: "7.9",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTslskXBSMy0kAhcDsCHmf2KmNMgva17TaGU2W59Sq-CLgibiIw",
        releaseDate: "2023",
        genre: "Action, Adventure, Comedy",
    },
    {
        title: "Blue Beetle",
        link: "https://www.imdb.com/title/tt9362930/?ref_=adv_li_tt",
        desc: "An alien scarab chooses Jaime Reyes to be its symbiotic host, bestowing the recent college graduate with a suit of armor that's capable of extraordinary powers, forever changing his destiny as he becomes the superhero known as Blue Beetle.",
        ratings: "6.5",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-k5W_6TMcJOjhLn1zu23IX-SN15_d3hkjCTLIaWPs0QW2DhxU",
        releaseDate: "2023",
        genre: "Action, Adventure, Sci-Fi",
    },
    {
        title: "Dungeons & Dragons: Honor Among Thieves",
        link: "https://www.imdb.com/title/tt2906216/?ref_=adv_li_tt",
        desc: "A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.",
        ratings: "7.3",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRyVoJwTTePsl7_q59ocw95BICBLAkeViDfgxmspYHpbMPEcRQ0",
        releaseDate: "2023",
        genre: "Action, Adventure, Comedy",
    },
    {
        title: "Gran Turismo",
        link: "https://www.imdb.com/title/tt4495098/?ref_=adv_li_tt",
        desc: "Based on the unbelievable, inspiring true story of a team of underdogs - a struggling, working-class gamer, a failed former race car driver, and an idealistic motorsport exec - who risk it all to take on the most elite sport in the world.",
        ratings: "7.4",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROMKu8mMzWbE08Hgh_FVX0GUn07mZa_PMo2YLJ4lPXq5146DoU",
        releaseDate: "2023",
        genre: "Action, Adventure, Drama",
    },
    {
        title: "Meg 2: The Trench",
        link: "https://www.imdb.com/title/tt9224104/?ref_=adv_li_tt",
        desc: "A research team encounters multiple threats while exploring the depths of the ocean, including a malevolent mining operation.",
        ratings: "5.2",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSMnMLOYARaIAuDNAejIcbXu3bWNcUyWKj87Pvh1XLooioIiRro",
        releaseDate: "2023",
        genre: "Action, Adventure, Horror",
    },
    {
        title: "Jailer",
        link: "https://www.imdb.com/title/tt11663228/?ref_=adv_li_tt",
        desc: "A retired jailer goes on a manhunt to find his son's killers. But the road leads him to a familiar, albeit a bit darker place. Can he emerge from this complex situation successfully?",
        ratings: "7.2",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRqK3_nPn_8UHFtyOFgDtrx1d_DfmngcZ3qbTLHZq7vbIrrllSx",
        releaseDate: "2023",
        genre: "Action, Comedy, Crime",
    },
    {
        title: "Retribution",
        link: "https://www.imdb.com/title/tt6906292/?ref_=adv_li_tt",
        desc: "A bank executive receives a bomb threat while driving his children to school that his car will explode if they stop and get out.",
        ratings: "5.3",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJBV2esPQkoh5xfRbSarswF9A36Num5iyEbnuk6DuP3CYgvM_L",
        releaseDate: "2023",
        genre: "Action, Crime, Drama",
    },
    {
        title: "The Equalizer",
        link: "https://www.imdb.com/title/tt0455944/?ref_=adv_li_tt",
        desc: "A man who believes he has put his mysterious past behind him cannot stand idly by when he meets a young girl under the control of ultra-violent Russian gangsters.",
        ratings: "7.2",
        status: "Available",
        image: "https://www.movienewsletters.net/photos/140326R1.jpg",
        releaseDate: "2014",
        genre: "Action, Crime, Thriller",
    },
    {
        title: "Mission: Impossible - Dead Reckoning Part One",
        link: "https://www.imdb.com/title/tt9603212/?ref_=adv_li_tt",
        desc: "Ethan Hunt and his IMF team must track down a dangerous weapon before it falls into the wrong hands.",
        ratings: "7.9",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRPunAXQI8_X7p1MYVmiRF-hSOinkCiCqca8p9_0vB22qS2ttjx",
        releaseDate: "2023",
        genre: "Action, Adventure, Thriller",
    },
    {
        title: "The Batman",
        link: "https://www.imdb.com/title/tt1877830/?ref_=adv_li_tt",
        desc: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
        ratings: "7.8",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRBkxgl2A2PhE_6tklFLT0bxn5NLhvhsnpXGhmXBt_zotrlVHmo",
        releaseDate: "2022",
        genre: "Action, Crime, Drama",
    },
    {
        title: "John Wick: Chapter 4",
        link: "https://www.imdb.com/title/tt10366206/?ref_=adv_li_tt",
        desc: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
        ratings: "7.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/John.Wick.Chapter.4.2023.jpg",
        releaseDate: "2023",
        genre: "Action, Crime, Thriller",
    },
    {
        title: "Avengers: Endgame",
        link: "https://www.imdb.com/title/tt4154796/?ref_=adv_li_tt",
        desc: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
        ratings: "8.4",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/Avengers.Endgame.2019.jpg",
        releaseDate: "2019",
        genre: "Action, Adventure, Drama",
    },
    {
        title: "Fast X",
        link: "https://www.imdb.com/title/tt5433140/?ref_=adv_li_tt",
        desc: "Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.",
        ratings: "5.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Fast.X.2023.jpg",
        releaseDate: "2023",
        genre: "Action, Adventure, Crime",
    },
    {
        title: "Heart of Stone",
        link: "https://www.imdb.com/title/tt13603966/?ref_=adv_li_tt",
        desc: "An intelligence operative for a shadowy global peacekeeping agency races to stop a hacker from stealing its most valuable and dangerous weapon.",
        ratings: "5.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Heart.of.Stone.2023.jpg",
        releaseDate: "2023",
        genre: "Action, Crime, Thriller",
    },
    {
        title: "The Dark Knight",
        link: "https://www.imdb.com/title/tt0468569/?ref_=adv_li_tt",
        desc: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        ratings: "9.0",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Dark.Knight.2008.jpg",
        releaseDate: "2008",
        genre: "Action, Crime, Drama",
    },
    {
        title: "The Covenant",
        link: "https://www.imdb.com/title/tt4873118/?ref_=adv_li_tt",
        desc: "During the war in Afghanistan, a local interpreter risks his own life to carry an injured sergeant across miles of grueling terrain.",
        ratings: "7.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Guy.Ritchies.the.Covenant.2023.jpg",
        releaseDate: "2023",
        genre: "Action, Drama, Thriller",
    },
    {
        title: "Hypnotic",
        link: "https://www.imdb.com/title/tt8080204/?ref_=adv_li_tt",
        desc: "A detective investigates a mystery involving his missing daughter and a secret government program.",
        ratings: "5.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Hypnotic.2023.jpg",
        releaseDate: "2023",
        genre: "Action, Mystery, Thriller",
    },
    {
        title: "The Hunger Games",
        link: "https://www.imdb.com/title/tt1392170/?ref_=adv_li_tt",
        desc: "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games: a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death.",
        ratings: "7.2",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/The%20Hunger%20Games.jpg",
        releaseDate: "2012",
        genre: "Action, Adventure, Sci-Fi",
    },
    {
        title: "Avatar: The Way of Water",
        link: "https://www.imdb.com/title/tt1630029/?ref_=adv_li_tt",
        desc: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
        ratings: "7.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Avatar.The.Way.of.Water.2022.jpg",
        releaseDate: "2022",
        genre: "Action, Adventure, Fantasy",
    },
    {
        title: "The Equalizer 2",
        link: "https://www.imdb.com/title/tt3766354/?ref_=adv_li_tt",
        desc: "Robert McCall serves an unflinching justice for the exploited and oppressed, but how far will he go when that is someone he loves?",
        ratings: "6.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Equalizer.2.2018.jpg",
        releaseDate: "2018",
        genre: "Action, Crime, Thriller",
    },
    {
        title: "65",
        link: "https://www.imdb.com/title/tt12261776/?ref_=adv_li_tt",
        desc: "An astronaut crash lands on a mysterious planet only to discover he's not alone.",
        ratings: "5.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/65.2023.jpg",
        releaseDate: "2023",
        genre: "Action, Adventure, Drama",
    },
    {
        title: "Dredd",
        link: "https://www.imdb.com/title/tt1343727/?ref_=adv_li_tt",
        desc: "In a violent, futuristic city where the police have the authority to act as judge, jury and executioner, a cop teams with a trainee to take down a gang that deals the reality-altering drug, SLO-MO.",
        ratings: "7.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Dredd.jpg",
        releaseDate: "2012",
        genre: "Action, Crime, Sci-Fi",
    },
    {
        title: "Dune",
        link: "https://www.imdb.com/title/tt1160419/?ref_=adv_li_tt",
        desc: "A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.",
        ratings: "8.0",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Dune.2021.jpg",
        releaseDate: "2021",
        genre: "Action, Adventure, Drama"
    },
    {
        title: "Transformers: Rise of the Beasts",
        link: "https://www.imdb.com/title/tt5090568/?ref_=adv_li_tt",
        desc: "During the '90s, a new faction of Transformers - the Maximals - join the Autobots as allies in the battle for Earth.",
        ratings: "6.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Transformers.Rise.of.the.Beasts.2023.jpg",
        releaseDate: "2023",
        genre: "Action, Adventure, Sci-Fi",
    },
    {
        title: "Inception",
        link: "https://www.imdb.com/title/tt1375666/?ref_=adv_li_tt",
        desc: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
        ratings: "8.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Inception.jpg",
        releaseDate: "2010",
        genre: "Action, Adventure, Sci-Fi",
    },
    {
        title: "Everything Everywhere All at Once",
        link: "https://www.imdb.com/title/tt6710474/?ref_=adv_li_tt",
        desc: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
        ratings: "7.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Everything.Everywhere.All.at.Once.2022.jpg",
        releaseDate: "2022",
        genre: "Action, Adventure, Comedy",
    },
    {
        title: "Spider-Man: No Way Home",
        link: "https://www.imdb.com/title/tt10872600/?ref_=adv_li_tt",
        desc: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/Spider.Man.No.Way.Home.2021.jpg",
        releaseDate: "2021",
        genre: "Action, Adventure, Fantasy",
    },
    {
        title: "Top Gun: Maverick",
        link: "https://www.imdb.com/title/tt1745960/?ref_=adv_li_tt",
        desc: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
        ratings: "8.3",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Top.Gun.Maverick.2022.jpg",
        releaseDate: "2022",
        genre: "Action, Drama",
    },
    {
        title: "Jurassic Park",
        link: "https://www.imdb.com/title/tt0107290/?ref_=adv_li_tt",
        desc: "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Jurassic%20Park.jpg",
        releaseDate: "1993",
        genre: "Action, Adventure, Sci-Fi",
    },
    {
        title: "The Matrix Resurrections",
        link: "https://www.imdb.com/title/tt10838180/?ref_=adv_li_tt",
        desc: "Return to a world of two realities: one, everyday life; the other, what lies behind it. To find out if his reality is a construct, to truly know himself, Mr. Anderson will have to choose to follow the white rabbit once more.",
        ratings: "5.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Matrix.Resurrections.2021.jpg",
        releaseDate: "2021",
        genre: "Action, Sci-Fi",
    },
    {
        title: "Aquaman",
        link: "https://www.imdb.com/title/tt1477834/?ref_=adv_li_tt",
        desc: "Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land.",
        ratings: "6.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Aquaman.2018.jpg",
        releaseDate: "2018",
        genre: "Action, Adventure, Fantasy",
    },
    {
        title: "To Catch a Killer",
        link: "https://www.imdb.com/title/tt10275534/?ref_=adv_li_tt",
        desc: "Baltimore. New Year's Eve. A talented but troubled police officer (Shailene Woodley) is recruited by the FBI's chief investigator (Ben Mendelsohn) to help profile and track down a disturbed individual terrorizing the city.",
        ratings: "6.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Misanthrope.2023.jpg",
        releaseDate: "2023",
        genre: "Action, Crime, Drama",
    },
    {
        title: "The Lord of the Rings: The Fellowship of the Ring",
        link: "https://www.imdb.com/title/tt0120737/?ref_=adv_li_tt",
        desc: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
        ratings: "8.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The%20Lord%20of%20the%20Rings%20%20The%20Fellowship%20of%20the%20Ring.jpg",
        releaseDate: "2001",
        genre: "Action, Adventure, Drama",
    },
    {
        title: "Tenet",
        link: "https://www.imdb.com/title/tt6723592/?ref_=adv_li_tt",
        desc: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
        ratings: "7.3",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Tenet.2020.jpg",
        releaseDate: "2020",
        genre: "Action, Sci-Fi, Thriller",
    },
    {
        title: "Bullet Train",
        link: "https://www.imdb.com/title/tt12593682/?ref_=adv_li_tt",
        desc: "Five assassins aboard a swiftly-moving bullet train find out that their missions have something in common.",
        ratings: "7.3",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Bullet.Train.2022.jpg",
        releaseDate: "2022",
        genre: "Action, Comedy, Thriller",
    },
    {
        title: "Gladiator",
        link: "https://www.imdb.com/title/tt0172495/?ref_=adv_li_tt",
        desc: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Gladiator.jpg",
        releaseDate: "2000",
        genre: "Action, Adventure, Drama",
    },
    {
        title: "Mad Max: Fury Road",
        link: "https://www.imdb.com/title/tt1392190/?ref_=adv_li_tt",
        desc: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper and a drifter named Max.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Mad.Max.Fury.Road.2015.jpg",
        releaseDate: "2015",
        genre: "Action, Adventure, Sci-Fi",
    },
    {
        title: "The Meg",
        link: "https://www.imdb.com/title/tt4779682/?ref_=adv_li_tt",
        desc: "A group of scientists exploring the Marianas Trench encounter the largest marine predator that has ever existed - the Megalodon.",
        ratings: "5.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Meg.2018.jpg",
        releaseDate: "2018",
        genre: "Action, Horror, Sci-Fi",
    },
    {
        title: "Heat",
        link: "https://www.imdb.com/title/tt0113277/?ref_=adv_li_tt",
        desc: "A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.",
        ratings: "8.3",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Heat.jpg",
        releaseDate: "1995",
        genre: "Action, Crime, Drama",
    },
    {
        title: "Blade Runner 2049",
        link: "https://www.imdb.com/title/tt1856101/?ref_=adv_li_tt",
        desc: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
        ratings: "8.0",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Blade.Runner.2049.2017.jpg",
        releaseDate: "2017",
        genre: "Action, Drama, Mystery",
    },
]






export const series = [
    {
        title: "The Wire",
        desc: "The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.",
        ratings: "9.3",
        status: "Available",
        image: "https://m.media-amazon.com/images/M/MV5BZmY5ZDMxODEtNWIwOS00NjdkLTkyMjktNWRjMDhmYjJjN2RmXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX140_CR0,0,140,209_AL_.jpg",
        releaseDate: "2002",
        genre: "Crime, Drama, Thriller",
    },
    {
        title: "The Sopranos",
        desc: "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.",
        ratings: "9.2",
        status: "Available",
        image: "https://m.media-amazon.com/images/M/MV5BNmU3MjkzZWQtOTk1Ni00OTNiLWJhMmMtNmEyN2JjZjUzZDUyXkEyXkFqcGdeQXVyNDIyNjA2MTk@._V1_UY209_CR3,0,140,209_AL_.jpg",
        releaseDate: "1999",
        genre: "Crime, Drama",
    },
    {
        title: "Breaking Bad",
        desc: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
        ratings: "9.5",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSSbIxdut987G-06iwjyGTtg6GQhafM-nG-Gtyc-9GMdrzPI9Ft",
        releaseDate: "2008",
        genre: "Crime, Drama, Thriller",
    },
    {
        title: "Better Call Saul",
        desc: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.",
        ratings: "9",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSAfbQzvGKy0oUKX3tKXOKirveHpqNU8fUxWNq6ghdDDLxeYxfw",
        releaseDate: "2015",
        genre: "Crime, Drama",

    },
    {
        title: "Game of Thrones",
        desc: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for a millennia.",
        ratings: "9.2",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR6fZCqFuwnsu7kHCgO_R3kHzzXrQr3_Vho8vsIR6EmeuaFi2ZY",
        releaseDate: "2011",
        genre: "Action, Adventure, Drama",
    },
    {
        title: "Sherlock",
        desc: "The quirky spin on Conan Doyle's iconic sleuth pitches him as a 'high-functioning sociopath' in modern-day London. Assisting him in his investigations: Afghanistan War vet John Watson, who's introduced to Holmes by a mutual acquaintance.",
        ratings: "9.1",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQFHMCMi3SM6HVf0M-Ua0zLlXgBvdsyTT8JL47mVS58uxEaEPse",
        releaseDate: "2010",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "Friends",
        desc: "Follows the personal and professional lives of six twenty to thirty year-old friends living in the Manhattan borough of New York City.",
        ratings: "8.9",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQqLYH_Sfv0dDGSzu6UhTmaYUo1OxBSTtUmRjZIqazHipy3K6Al",
        releaseDate: "1994",
        genre: "Comedy, Romance",
    },
    {
        title: "House",
        desc: "An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come his way using his crack team of doctors and his wits.",
        ratings: "8.7",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ5PZTuvkysbhL2DSfDdyF99K9DuHbczj6xICF-0MVLtNHBJ89i",
        releaseDate: "2004",
        genre: "Drama, Mystery",
    },
    {
        title: "The Americans",
        desc: "At the height of the Cold War, two Russian agents pose as the average American couple, complete with family.",
        ratings: "8.4",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWSxEMxvpI7ZvaK97TT-gqME2nPYtdHhlDBO4hEB-KnUshq-Qr",
        releaseDate: "2013",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "Peaky Blinders",
        desc: "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
        ratings: "8.8",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTUIJZiEThsXozTY2jFF1R9UQpLW3cWILFpMdbTLSwRdxGFnJro",
        releaseDate: "2013",
        genre: "Crime, Drama",
    },
    {
        title: "Fargo",
        desc: "Various chronicles of deception, intrigue, and murder in and around frozen Minnesota. All of these tales mysteriously lead back one way or another to Fargo, North Dakota.",
        ratings: "8.9",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTslskXBSMy0kAhcDsCHmf2KmNMgva17TaGU2W59Sq-CLgibiIw",
        releaseDate: "2014",
        genre: "Crime, Drama, Thriller",
    },
    {
        title: "How I Met Your Mother",
        desc: "A father recounts to his children - through a series of flashbacks - the journey he and his four best friends took leading up to him meeting their mother.",
        ratings: "8.3",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-k5W_6TMcJOjhLn1zu23IX-SN15_d3hkjCTLIaWPs0QW2DhxU",
        releaseDate: "2005",
        genre: "Comedy, Drama, Romance",
    },
    {
        title: "Lost",
        desc: "The survivors of a plane crash are forced to work together in order to survive on a seemingly deserted tropical island.",
        ratings: "8.3",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRyVoJwTTePsl7_q59ocw95BICBLAkeViDfgxmspYHpbMPEcRQ0",
        releaseDate: "2004",
        genre: " Adventure, Drama, Fantasy",
    },
    {
        title: "Mad Men",
        desc: "A drama about one of New York's most prestigious ad agencies at the beginning of the 1960s, focusing on one of the firm's most mysterious but extremely talented ad executives, Donald Draper.",
        ratings: "8.7",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROMKu8mMzWbE08Hgh_FVX0GUn07mZa_PMo2YLJ4lPXq5146DoU",
        releaseDate: "2007",
        genre: "Drama",
    },
    {
        title: "True Detective",
        desc: "Anthology series in which police investigations unearth the personal and professional secrets of those involved, both within and outside the law.",
        ratings: "8.9",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSMnMLOYARaIAuDNAejIcbXu3bWNcUyWKj87Pvh1XLooioIiRro",
        releaseDate: "2014",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "Firefly",
        desc: "Five hundred years in the future, a renegade crew aboard a small spacecraft tries to survive as they travel the unknown parts of the galaxy and evade warring factions as well as authority agents out to get them.",
        ratings: "9",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRqK3_nPn_8UHFtyOFgDtrx1d_DfmngcZ3qbTLHZq7vbIrrllSx",
        releaseDate: "2002",
        genre: "Adventure, Drama, Sci-Fi",
    },
    {
        title: "Boardwalk Empire",
        desc: "An Atlantic City politician plays both sides of the law by conspiring with gangsters during the Prohibition era.",
        ratings: "8.6",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJBV2esPQkoh5xfRbSarswF9A36Num5iyEbnuk6DuP3CYgvM_L",
        releaseDate: "2010",
        genre: "Crime, Drama",
    },
    {
        title: "Doctor Who",
        desc: "The further adventures in time and space of the alien adventurer known as the Doctor and his companions from planet Earth.",
        ratings: "8.6",
        status: "Available",
        image: "https://www.movienewsletters.net/photos/140326R1.jpg",
        releaseDate: "2005",
        genre: "Adventure, Drama, Sci-Fi",
    },
    {
        title: "Luther",
        desc: "DCI John Luther is a near-genius murder detective whose brilliant mind can't always save him from the dangerous violence of his passions.",
        ratings: "8.4",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRPunAXQI8_X7p1MYVmiRF-hSOinkCiCqca8p9_0vB22qS2ttjx",
        releaseDate: "2010",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "Californication",
        desc: "A writer tries to juggle his career, his relationship with his daughter and his ex-girlfriend, as well as his appetite for beautiful women.",
        ratings: "8.3",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRBkxgl2A2PhE_6tklFLT0bxn5NLhvhsnpXGhmXBt_zotrlVHmo",
        releaseDate: "2007",
        genre: "Comedy, Drama",
    },
    {
        title: "Twin Peaks",
        desc: "An idiosyncratic FBI agent investigates the murder of a young woman in the even more idiosyncratic town of Twin Peaks.",
        ratings: "8.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/John.Wick.Chapter.4.2023.jpg",
        releaseDate: "1990",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "The X-Files",
        desc: "Two F.B.I. Agents, Fox Mulder the believer and Dana Scully the skeptic, investigate the strange and unexplained, while hidden forces work to impede their efforts.",
        ratings: "8.6",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/Avengers.Endgame.2019.jpg",
        releaseDate: "1993",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "The Night Of",
        desc: "After a night of partying with a woman he picked up, a man wakes up to find her stabbed to death and is charged with her murder.",
        ratings: "8.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Fast.X.2023.jpg",
        releaseDate: "2016",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "Black Mirror",
        desc: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
        ratings: "8.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Heart.of.Stone.2023.jpg",
        releaseDate: "2011",
        genre: "Drama, Mystery, Sci-Fi",
    },
    {
        title: "House of Cards",
        desc: "A Congressman works with his equally conniving wife to exact revenge on the people who betrayed him.",
        ratings: "8.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Dark.Knight.2008.jpg",
        releaseDate: "2013",
        genre: "Drama",
    },
    {
        title: "Dexter",
        desc: "He's smart. He's lovable. He's Dexter Morgan, America's favorite serial killer, who spends his days solving crimes and nights committing them.",
        ratings: "8.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Guy.Ritchies.the.Covenant.2023.jpg",
        releaseDate: "2006",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "Silicon Valley",
        desc: "Follows the struggle of Richard Hendricks, a Silicon Valley engineer trying to build his own company called Pied Piper.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Hypnotic.2023.jpg",
        releaseDate: "2014",
        genre: "Comedy",
    },
    {
        title: "Fringe",
        desc: "An F.B.I. agent is forced to work with an institutionalized scientist and his son in order to rationalize a brewing storm of unexplained phenomena.",
        ratings: "8.4",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/The%20Hunger%20Games.jpg",
        releaseDate: "2008",
        genre: "Drama, Mystery, Sci-Fi",
    },
    {
        title: "Mr. Robot",
        desc: "Elliot, a brilliant but highly unstable young cyber-security engineer and vigilante hacker, becomes a key figure in a complex game of global dominance when he and his shadowy allies try to take down the corrupt corporation he works for.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Avatar.The.Way.of.Water.2022.jpg",
        releaseDate: "2015",
        genre: "Crime, Drama, Thriller",
    },
    {
        title: "It's Always Sunny in Philadelphia",
        desc: "Five friends with big egos and small brains are the proprietors of an Irish pub in Philadelphia.",
        ratings: "8.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Equalizer.2.2018.jpg",
        releaseDate: "2005",
        genre: "Comedy",
    },
    {
        title: "Person of Interest",
        desc: "An ex-CIA agent and a wealthy programmer save lives via a surveillance AI that sends them the identities of civilians involved in impending crimes. However, the details of the crimes, including the civilians' roles, are left a mystery.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/65.2023.jpg",
        releaseDate: "2011",
        genre: "Action, Crime, Drama",
    },
    {
        title: "Castle",
        desc: "A suave, best-selling author teams up with a strait-laced detective to solve crimes in New York City.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Dredd.jpg",
        releaseDate: "2009",
        genre: "Comedy, Crime, Drama",
    },
    {
        title: "Atlanta",
        desc: "Earn and his cousin, Alfred, try to make their way in the world through Atlanta's rap scene. Along the way they come face-to-face with social and economic issues touching on race, relationships, poverty, status and parenthood.",
        ratings: "8.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Dune.2021.jpg",
        releaseDate: "2016",
        genre: "Comedy, Drama, Music"
    },
    {
        title: "Shameless",
        desc: "A scrappy, feisty, fiercely loyal Chicago family makes no apologies.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Transformers.Rise.of.the.Beasts.2023.jpg",
        releaseDate: "2011",
        genre: "Comedy, Drama",
    },
    {
        title: "Brooklyn Nine-Nine",
        desc: "Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD's 99th Precinct.",
        ratings: "8.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Inception.jpg",
        releaseDate: "2013",
        genre: "Comedy, Crime",
    },
    {
        title: "The Walking Dead",
        desc: "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Everything.Everywhere.All.at.Once.2022.jpg",
        releaseDate: "2010",
        genre: "Drama, Horror, Thriller",
    },
    {
        title: "Leverage",
        desc: "A crew of high-tech crooks attempt to steal from wealthy criminals and corrupt businessmen.",
        ratings: "7.9",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/Spider.Man.No.Way.Home.2021.jpg",
        releaseDate: "2008",
        genre: "Crime, Mystery, Thriller",
    },
    {
        title: "Daredevil",
        desc: "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil.",
        ratings: "8.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Top.Gun.Maverick.2022.jpg",
        releaseDate: "2015",
        genre: "Action, Crime, Drama",
    },
    {
        title: "The Big Bang Theory",
        desc: "A woman who moves into an apartment across the hall from two brilliant but socially awkward physicists shows them how little they know about life outside of the laboratory.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Jurassic%20Park.jpg",
        releaseDate: "2007",
        genre: "Comedy, Romance",
    },
    {
        title: "Stranger Things",
        desc: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
        ratings: "8.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Matrix.Resurrections.2021.jpg",
        releaseDate: "2016",
        genre: "Drama, Fantasy, Horror",
    },
    {
        title: "Narcos (I)",
        desc: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.",
        ratings: "8.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Aquaman.2018.jpg",
        releaseDate: "2015",
        genre: "Biography, Crime, Drama",
    },
    {
        title: "Hannibal",
        desc: "Explores the early relationship between renowned psychiatrist Hannibal Lecter and a young FBI criminal profiler who is haunted by his ability to empathize with serial killers.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Misanthrope.2023.jpg",
        releaseDate: "2013",
        genre: "Crime, Drama, Horror",
    },
    {
        title: "Prison Break",
        desc: "A structural engineer installs himself in a prison he helped design, in order to save his falsely accused brother from a death sentence by breaking themselves out from the inside.",
        ratings: "8.3",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The%20Lord%20of%20the%20Rings%20%20The%20Fellowship%20of%20the%20Ring.jpg",
        releaseDate: "2005",
        genre: "Action, Crime, Drama",
    },
    {
        title: "Westworld",
        desc: "At the intersection of the near future and the reimagined past, waits a world in which every human appetite can be indulged without consequence.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Tenet.2020.jpg",
        releaseDate: "2016",
        genre: "Drama, Mystery, Sci-Fi",
    },
    {
        title: "Modern Family",
        desc: "Three different but related families face trials and tribulations in their own uniquely comedic ways.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Bullet.Train.2022.jpg",
        releaseDate: "2009",
        genre: "Comedy, Drama, Romance",
    },
    {
        title: "Jessica Jones",
        desc: "Following the tragic end of her brief superhero career, Jessica Jones tries to rebuild her life as a private investigator, dealing with cases involving people with remarkable abilities in New York City.",
        ratings: "7.9",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Gladiator.jpg",
        releaseDate: "2015",
        genre: "Action, Crime, Drama",
    },
    {
        title: "The Night Manager",
        desc: "The night manager of a Cairo hotel is recruited to infiltrate an arms dealer's inner circle.",
        ratings: "8.0",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Mad.Max.Fury.Road.2015.jpg",
        releaseDate: "2016",
        genre: "Crime, Drama, Mystery",
    },
    {
        title: "American Horror Story",
        desc: "An anthology series centering on different characters and locations, showcasing different aspects of horror.",
        ratings: "8.0",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Meg.2018.jpg",
        releaseDate: "2011",
        genre: "Drama, Horror, Sci-Fi",
    },
    {
        title: "Preacher",
        desc: "After a supernatural event at his church, a preacher enlists the help of a vampire and his ex to find God.",
        ratings: "7.9",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Heat.jpg",
        releaseDate: "2016",
        genre: "Action, Adventure, Comedy",
    },
    {
        title: "Supernatural",
        desc: "Two brothers follow their father's footsteps as hunters, fighting evil supernatural beings of many kinds, including monsters, demons, and gods that roam the earth.",
        ratings: "8.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Blade.Runner.2049.2017.jpg",
        releaseDate: "2005",
        genre: "Drama, Fantasy, Horror",
    },
]





export const documentaries = [
    {
        title: "Stop Making Sense",
        desc: "Considered by critics as the greatest concert film of all time, the live performance was shot over the course of three nights at Hollywood's Pantages Theater in December of 1983 and features Talking Heads' most memorable songs.",
        ratings: "8.7",
        status: "Available",
        image: "https://m.media-amazon.com/images/M/MV5BMjE3MjhkM2YtNzg2Yi00ZDdlLWE1MDMtNDUxYmFmMjY3OWZkXkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_UX67_CR0,0,67,98_AL_.jpg",
        releaseDate: "1984",
        genre: "Documentary, Music",
    },
    {
        title: "Ice Cold: Murder, Coffee and Jessica Wongso",
        desc: "This documentary delves into the unanswered questions surrounding the trial of Jessica Wongso years after the death of her best friend, Mirna Salihin.",
        ratings: "6.1",
        status: "Available",
        image: "https://m.media-amazon.com/images/M/MV5BNmU3MjkzZWQtOTk1Ni00OTNiLWJhMmMtNmEyN2JjZjUzZDUyXkEyXkFqcGdeQXVyNDIyNjA2MTk@._V1_UY209_CR3,0,140,209_AL_.jpg",
        releaseDate: "2023",
        genre: "Documentary, Crime",
    },
    {
        title: "Take Care of Maya",
        desc: "As a medical team tries to understand 10-year-old Maya Kowalski's rare illness, they begin to question her parents. Suddenly, Maya is in state custody - despite a family desperate to bring their daughter home.",
        ratings: "7.8",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSSbIxdut987G-06iwjyGTtg6GQhafM-nG-Gtyc-9GMdrzPI9Ft",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "After Death",
        desc: "Based on real near-death experiences, After Death explores the afterlife with the guidance of New York Times bestselling authors, medical experts, scientists, and survivors that shed a light on what awaits us.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSAfbQzvGKy0oUKX3tKXOKirveHpqNU8fUxWNq6ghdDDLxeYxfw",
        releaseDate: "2023",
        genre: "Documentary",

    },
    {
        title: "The Mission",
        desc: "26-year-old American missionary John Chau was killed as he attempted to make contact with an Indigenous group off the coast of India, one of the last communities on the planet still living in isolation.",
        ratings: "7.7",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR6fZCqFuwnsu7kHCgO_R3kHzzXrQr3_Vho8vsIR6EmeuaFi2ZY",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Kelce",
        desc: "Highlights Kelce's 2022-23 season, which started with him having to make one of the hardest decisions a professional athlete would ever have to make: Is it time to retire yet?",
        ratings: "8.3",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQFHMCMi3SM6HVf0M-Ua0zLlXgBvdsyTT8JL47mVS58uxEaEPse",
        releaseDate: "20123",
        genre: "Documentary, Sport",
    },
    {
        title: "The Ringleader: The Case of the Bling Ring",
        desc: "Rachel Lee, the so-called teenage mastermind behind a string of high-profile celebrity robberies in 2008 and 2009, shares what motivated her to rally her friends to break into celebrity homes in Hollywood to ransack and steal.",
        ratings: "5.3",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQqLYH_Sfv0dDGSzu6UhTmaYUo1OxBSTtUmRjZIqazHipy3K6Al",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Race to the Summit",
        desc: "Fearless alpine climbers Ueli Steck and Dani Arnold enter into a death-defying rivalry to set speed records on the Swiss Alps' great north faces.",
        ratings: "6.9",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ5PZTuvkysbhL2DSfDdyF99K9DuHbczj6xICF-0MVLtNHBJ89i",
        releaseDate: "2023",
        genre: "Documentary, Adventure, Sport",
    },
    {
        title: "The Act of Killing",
        desc: "A documentary which challenges former Indonesian death-squad leaders to reenact their mass-killings in whichever cinematic genres they wish, including classic Hollywood crime scenarios and lavish musical numbers.",
        ratings: "8.2",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWSxEMxvpI7ZvaK97TT-gqME2nPYtdHhlDBO4hEB-KnUshq-Qr",
        releaseDate: "2012",
        genre: "Documentary, Biography, Crime",
    },
    {
        title: "The Deepest Breath",
        desc: "A champion and expert safety diver seemed destined for one another. Despite different paths taken, they meet at the pinnacle of the free-diving world, experiencing the thrilling rewards and inescapable risks of chasing dreams through the depths of the ocean.",
        ratings: "7.7",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTUIJZiEThsXozTY2jFF1R9UQpLW3cWILFpMdbTLSwRdxGFnJro",
        releaseDate: "2023",
        genre: "Documentary, Adventure, Sport",
    },
    {
        title: "Joan Baez I Am a Noise",
        desc: "At the end of a 60-year career, legendary singer and activist Joan Baez takes an honest look back and a deep look inward as she tries to make sense of her large, history-making life, and the personal struggles she's kept private.",
        ratings: "8.0",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTslskXBSMy0kAhcDsCHmf2KmNMgva17TaGU2W59Sq-CLgibiIw",
        releaseDate: "2023",
        genre: "Documentary, Biography, Music",
    },
    {
        title: "Harley & Katya",
        desc: "A feature Documentary about Indigenous Australian figure skater Harley Windsor and his young Russian pair skating partner Ekaterina Alexandrovskaya. This unlikely duo made history, but at what cost?",
        ratings: "7.3",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-k5W_6TMcJOjhLn1zu23IX-SN15_d3hkjCTLIaWPs0QW2DhxU",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Superpower",
        desc: "Follows the events happening in Ukraine and the truth about Russia's invasion of the country.",
        ratings: "5.4",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRyVoJwTTePsl7_q59ocw95BICBLAkeViDfgxmspYHpbMPEcRQ0",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "The Saint of Second Chances",
        desc: "Mike Veeck, son of legendary Major League Baseball owner Bill Veeck, blows up his father's career and then spends the next few decades learning the value of a second chance.",
        ratings: "7.6",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROMKu8mMzWbE08Hgh_FVX0GUn07mZa_PMo2YLJ4lPXq5146DoU",
        releaseDate: "2023",
        genre: "Documentary, Biography, Drama",
    },
    {
        title: "What Is a Woman?",
        desc: "Political commentator Matt Walsh explores the changing concepts of sex and gender in the digital age, particularly the transgender rights movement, anti-transgender bigotry, and what it means to be a woman.",
        ratings: "8.2",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSMnMLOYARaIAuDNAejIcbXu3bWNcUyWKj87Pvh1XLooioIiRro",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Porn to Be Free",
        desc: "Porno & libertà is a film documentary about the generation who fought against puritanism and censorship to defend freedom of speech and sexual freedom.",
        ratings: "6.1",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRqK3_nPn_8UHFtyOFgDtrx1d_DfmngcZ3qbTLHZq7vbIrrllSx",
        releaseDate: "2016",
        genre: "Documentary",
    },
    {
        title: "Hotel Coolgardie",
        desc: "On a dusty highway between Australia's most isolated city and its largest gold pit lies Coolgardie - where the arrival every three months of a new pair of foreign backpackers to work the the only bar in town is a keenly anticipated event.",
        ratings: "6.8",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJBV2esPQkoh5xfRbSarswF9A36Num5iyEbnuk6DuP3CYgvM_L",
        releaseDate: "2016",
        genre: "Documentary",
    },
    {
        title: "The Darkness within La Luz del Mundo",
        desc: "In this gut-wrenching documentary, survivors share their stories of how they were abused by three generations of La Luz del Mundo church leaders.",
        ratings: "7.0",
        status: "Available",
        image: "https://www.movienewsletters.net/photos/140326R1.jpg",
        releaseDate: "2023",
        genre: "Documentary, Crime",
    },
    {
        title: "Rosa Peral's Tapes",
        desc: "This true-crime documentary film features Rosa Peral's first interview from prison since she was convicted of murdering her partner aided by an ex-lover.",
        ratings: "5.3",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRPunAXQI8_X7p1MYVmiRF-hSOinkCiCqca8p9_0vB22qS2ttjx",
        releaseDate: "2023",
        genre: "Documentary, Crime",
    },
    {
        title: "The Devil on Trial",
        desc: "Using reenactments and home videos, this dark documentary investigates the apparent possession of a young boy and the brutal murder that followed.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRBkxgl2A2PhE_6tklFLT0bxn5NLhvhsnpXGhmXBt_zotrlVHmo",
        releaseDate: "2023",
        genre: "Documentary, Crime, Horror",
    },
    {
        title: "20 Days in Mariupol",
        desc: "As the Russian invasion begins, a team of Ukrainian journalists trapped in the besieged city of Mariupol struggle to continue their work documenting the war's atrocities.",
        ratings: "8.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/John.Wick.Chapter.4.2023.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Monster Inside: America's Most Extreme Haunted House",
        desc: "Follows the story of Russ McKamey. The Navy Veteran turned master of horror, who lures horror enthusiasts into his web.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://fzmovies.net/imdb_images/Avengers.Endgame.2019.jpg",
        releaseDate: "2023",
        genre: "Documentary, Crime, Horror",
    },
    {
        title: "Koyaanisqatsi",
        desc: "A collection of expertly photographed phenomena with no conventional plot. The footage focuses on nature, humanity, and the relationship between them.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Fast.X.2023.jpg",
        releaseDate: "1982",
        genre: "Documentary, Music",
    },
    {
        title: "Deep Rising",
        desc: "The fate of the planet's last untouched wilderness, the deep ocean, is under threat as a secretive organization is about to allow massive extraction of seabed metals to address the world's energy crisis.",
        ratings: "7.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Heart.of.Stone.2023.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Dear Child",
        desc: "Set in a rehabilitation centre on the edge of the jungle, Dear Child follows a group of kids who have been rescued from the drug war, as they learn to become children again and not soldiers or drug addicts.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Dark.Knight.2008.jpg",
        releaseDate: "2020",
        genre: "Documentary",
    },
    {
        title: "Grizzly Man",
        desc: "A devastating and heart-rending take on grizzly bear activists Timothy Treadwell and Amie Huguenard, who were killed in October of 2003 while living among grizzly bears in Alaska.",
        ratings: "7.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Guy.Ritchies.the.Covenant.2023.jpg",
        releaseDate: "2005",
        genre: "Documentary, Biography",
    },
    {
        title: "Jackass Forever",
        desc: "After 11 years, the Jackass crew is back for another crusade.",
        ratings: "6.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Hypnotic.2023.jpg",
        releaseDate: "2022",
        genre: "Documentary, Action, Comedy",
    },
    {
        title: "Free Solo",
        desc: "Alex Honnold faces the biggest challenge of his career, climbing El Capitan in Yosemite National Park. He pursues it Free Solo which means climbing without a rope and alone.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/The%20Hunger%20Games.jpg",
        releaseDate: "2018",
        genre: "Documentary, Adventure, Sport",
    },
    {
        title: "Baraka",
        desc: "A collection of expertly photographed scenes of human life and religion.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Avatar.The.Way.of.Water.2022.jpg",
        releaseDate: "1992",
        genre: "Documentary",
    },
    {
        title: "Still: A Michael J. Fox Movie (II)",
        desc: "Follows the life of beloved actor and advocate Michael J. Fox, exploring his personal and professional triumphs and travails, and what happens when an incurable optimist confronts an incurable disease.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Equalizer.2.2018.jpg",
        releaseDate: "2023",
        genre: "Documentary, Biography",
    },
    {
        title: "Häxan",
        desc: "Fictionalized documentary showing the evolution of witchcraft, from its pagan roots to its confusion with hysteria in Eastern Europe.",
        ratings: "7.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/65.2023.jpg",
        releaseDate: "1922",
        genre: "Documentary, Fantasy, Horror",
    },
    {
        title: "Police State",
        desc: "Movie by filmmaker Dinesh D'Souza which claims federal organizations, like the FBI, CIA, and DOJ are corrupt, and are unfairly and selectively targeting Christians, conservatives, and republicans.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://fzmovies.host/imdb_images/Dredd.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "The Last Waltz",
        desc: "A film account and presentation of the final concert of The Band.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Dune.2021.jpg",
        releaseDate: "1978",
        genre: "Documentary, Biography, Music"
    },
    {
        title: "Faces of Death",
        desc: "A collection of death scenes, ranging from TV material to homemade super 8 movies.",
        ratings: "4.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Transformers.Rise.of.the.Beasts.2023.jpg",
        releaseDate: "1978",
        genre: "Documentary, Horror",
    },
    {
        title: "Moment of Contact",
        desc: "Is an exploration of extraterrestrial encounters centered on a series of events in 1996 when citizens of Varginha, Brazil, reported seeing a UFO crash and one or more strange creatures.",
        ratings: "7.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Inception.jpg",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Sticky: A (Self) Love Story",
        desc: "'Sticky' is everything your mother was too embarrassed to tell you about masturbation, in one stimulating documentary.",
        ratings: "6.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Everything.Everywhere.All.at.Once.2022.jpg",
        releaseDate: "2016",
        genre: "Documentary, Comedy",
    },
    {
        title: "Skin: A History of Nudity in the Movies",
        desc: "The definitive documentary on the history of nudity in feature films, from the early silent days to the present, studying the changes in morality that led to the use of nudity in films, while emphasizing the political, sociological, and artistic changes that shaped that history.",
        ratings: "6.7",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/Spider.Man.No.Way.Home.2021.jpg",
        releaseDate: "2020",
        genre: "Documentary, History",
    },
    {
        title: "Alien Endgame",
        desc: "It follows former members of the U.S. military as they break their silence about the massive cover-up of their terrifying UFO close encounters.",
        ratings: "5.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Top.Gun.Maverick.2022.jpg",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Inside Job",
        desc: "Takes a closer look at what brought about the 2008 financial meltdown.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Jurassic%20Park.jpg",
        releaseDate: "2010",
        genre: "Documentary, Crime",
    },
    {
        title: "Carlos",
        desc: "Follows Santana's journey from 14-year-old street musician to a 10-time Grammy winning global sensation. Features unseen archival footage and tracks.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Matrix.Resurrections.2021.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Samsara (I)",
        desc: "Filmed over nearly five years in twenty-five countries on five continents, and shot on seventy-millimetre film, Samsara transports us to the varied worlds of sacred grounds, disaster zones, industrial complexes, and natural wonders.",
        ratings: "8.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Aquaman.2018.jpg",
        releaseDate: "2011",
        genre: "Documentary, Music",
    },
    {
        title: "Grey Gardens",
        desc: "Meet a mother and daughter, high-society dropouts, reclusive cousins of Jackie O., managing to thrive together amid the decay and disorder of their East Hampton, NY, mansion, making for an eerily ramshackle echo of the American Camelot.",
        ratings: "7.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Misanthrope.2023.jpg",
        releaseDate: "1975",
        genre: "Documentary, Comedy, Drama",
    },
    {
        title: "The Social Dilemma",
        desc: "Explores the dangerous human impact of social networking; tech experts sound the alarm on their own creations.",
        ratings: "7.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The%20Lord%20of%20the%20Rings%20%20The%20Fellowship%20of%20the%20Ring.jpg",
        releaseDate: "2020",
        genre: "Documentary, Drama",
    },
    {
        title: "My Octopus Teacher",
        desc: "A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Tenet.2020.jpg",
        releaseDate: "2020",
        genre: "Documentary",
    },
    {
        title: "Stylebender",
        desc: "It follows a boy fighting to become the man he was destined to be. Will he find something to fight for, or will he become what he hates the most?",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Bullet.Train.2022.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Tickled",
        desc: "Journalist David Farrier stumbles upon a mysterious tickling competition online. As he delves deeper he comes up against fierce resistance, but that doesn't stop him getting to the bottom of a story stranger than fiction.",
        ratings: "7.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Gladiator.jpg",
        releaseDate: "2016",
        genre: "Documentary, Crime, Mystery",
    },
    {
        title: "David Beckham: Infamous",
        desc: "David Beckham, a household name, footballing icon and at one point the most hated man in England. A comprehensive look at David Beckham's footballing career focusing on his England redemption, World Cup dreams, trial by media and becoming brand Becks.",
        ratings: "4.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Mad.Max.Fury.Road.2015.jpg",
        releaseDate: "2022",
        genre: "Documentary, Biography, Sport",
    },
    {
        title: "Dear Zachary: A Letter to a Son About His Father",
        desc: "A filmmaker decides to memorialize a murdered friend when his friend's ex-girlfriend announces she is expecting his son.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Meg.2018.jpg",
        releaseDate: "2008",
        genre: "Documentary, Biography, Crime",
    },
    {
        title: "All the Beauty and the Bloodshed",
        desc: "Follows the life of artist Nan Goldin and the downfall of the Sackler family, the pharmaceutical dynasty who was greatly responsible for the opioid epidemic's unfathomable death toll.",
        ratings: "7.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Heat.jpg",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Smoke Sauna Sisterhood",
        desc: "In the darkness of a smoke sauna, women share their innermost secrets and intimate experiences, washing off the shame trapped in their bodies and regaining their strength through a sense of communion.",
        ratings: "8.0",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Blade.Runner.2049.2017.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
]





export const anime = [
    {
        title: "Stop Making Sense",
        desc: "Considered by critics as the greatest concert film of all time, the live performance was shot over the course of three nights at Hollywood's Pantages Theater in December of 1983 and features Talking Heads' most memorable songs.",
        ratings: "8.7",
        status: "Available",
        image: "https://m.media-amazon.com/images/M/MV5BMjE3MjhkM2YtNzg2Yi00ZDdlLWE1MDMtNDUxYmFmMjY3OWZkXkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_UX67_CR0,0,67,98_AL_.jpg",
        releaseDate: "1984",
        genre: "Documentary, Music",
    },
    {
        title: "Ice Cold: Murder, Coffee and Jessica Wongso",
        desc: "This documentary delves into the unanswered questions surrounding the trial of Jessica Wongso years after the death of her best friend, Mirna Salihin.",
        ratings: "6.1",
        status: "Available",
        image: "https://m.media-amazon.com/images/M/MV5BNmU3MjkzZWQtOTk1Ni00OTNiLWJhMmMtNmEyN2JjZjUzZDUyXkEyXkFqcGdeQXVyNDIyNjA2MTk@._V1_UY209_CR3,0,140,209_AL_.jpg",
        releaseDate: "2023",
        genre: "Documentary, Crime",
    },
    {
        title: "Take Care of Maya",
        desc: "As a medical team tries to understand 10-year-old Maya Kowalski's rare illness, they begin to question her parents. Suddenly, Maya is in state custody - despite a family desperate to bring their daughter home.",
        ratings: "7.8",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSSbIxdut987G-06iwjyGTtg6GQhafM-nG-Gtyc-9GMdrzPI9Ft",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "After Death",
        desc: "Based on real near-death experiences, After Death explores the afterlife with the guidance of New York Times bestselling authors, medical experts, scientists, and survivors that shed a light on what awaits us.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSAfbQzvGKy0oUKX3tKXOKirveHpqNU8fUxWNq6ghdDDLxeYxfw",
        releaseDate: "2023",
        genre: "Documentary",

    },
    {
        title: "The Mission",
        desc: "26-year-old American missionary John Chau was killed as he attempted to make contact with an Indigenous group off the coast of India, one of the last communities on the planet still living in isolation.",
        ratings: "7.7",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR6fZCqFuwnsu7kHCgO_R3kHzzXrQr3_Vho8vsIR6EmeuaFi2ZY",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Kelce",
        desc: "Highlights Kelce's 2022-23 season, which started with him having to make one of the hardest decisions a professional athlete would ever have to make: Is it time to retire yet?",
        ratings: "8.3",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQFHMCMi3SM6HVf0M-Ua0zLlXgBvdsyTT8JL47mVS58uxEaEPse",
        releaseDate: "20123",
        genre: "Documentary, Sport",
    },
    {
        title: "The Ringleader: The Case of the Bling Ring",
        desc: "Rachel Lee, the so-called teenage mastermind behind a string of high-profile celebrity robberies in 2008 and 2009, shares what motivated her to rally her friends to break into celebrity homes in Hollywood to ransack and steal.",
        ratings: "5.3",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQqLYH_Sfv0dDGSzu6UhTmaYUo1OxBSTtUmRjZIqazHipy3K6Al",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Race to the Summit",
        desc: "Fearless alpine climbers Ueli Steck and Dani Arnold enter into a death-defying rivalry to set speed records on the Swiss Alps' great north faces.",
        ratings: "6.9",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ5PZTuvkysbhL2DSfDdyF99K9DuHbczj6xICF-0MVLtNHBJ89i",
        releaseDate: "2023",
        genre: "Documentary, Adventure, Sport",
    },
    {
        title: "The Act of Killing",
        desc: "A documentary which challenges former Indonesian death-squad leaders to reenact their mass-killings in whichever cinematic genres they wish, including classic Hollywood crime scenarios and lavish musical numbers.",
        ratings: "8.2",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWSxEMxvpI7ZvaK97TT-gqME2nPYtdHhlDBO4hEB-KnUshq-Qr",
        releaseDate: "2012",
        genre: "Documentary, Biography, Crime",
    },
    {
        title: "The Deepest Breath",
        desc: "A champion and expert safety diver seemed destined for one another. Despite different paths taken, they meet at the pinnacle of the free-diving world, experiencing the thrilling rewards and inescapable risks of chasing dreams through the depths of the ocean.",
        ratings: "7.7",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTUIJZiEThsXozTY2jFF1R9UQpLW3cWILFpMdbTLSwRdxGFnJro",
        releaseDate: "2023",
        genre: "Documentary, Adventure, Sport",
    },
    {
        title: "Joan Baez I Am a Noise",
        desc: "At the end of a 60-year career, legendary singer and activist Joan Baez takes an honest look back and a deep look inward as she tries to make sense of her large, history-making life, and the personal struggles she's kept private.",
        ratings: "8.0",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTslskXBSMy0kAhcDsCHmf2KmNMgva17TaGU2W59Sq-CLgibiIw",
        releaseDate: "2023",
        genre: "Documentary, Biography, Music",
    },
    {
        title: "Harley & Katya",
        desc: "A feature Documentary about Indigenous Australian figure skater Harley Windsor and his young Russian pair skating partner Ekaterina Alexandrovskaya. This unlikely duo made history, but at what cost?",
        ratings: "7.3",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-k5W_6TMcJOjhLn1zu23IX-SN15_d3hkjCTLIaWPs0QW2DhxU",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Superpower",
        desc: "Follows the events happening in Ukraine and the truth about Russia's invasion of the country.",
        ratings: "5.4",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRyVoJwTTePsl7_q59ocw95BICBLAkeViDfgxmspYHpbMPEcRQ0",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "The Saint of Second Chances",
        desc: "Mike Veeck, son of legendary Major League Baseball owner Bill Veeck, blows up his father's career and then spends the next few decades learning the value of a second chance.",
        ratings: "7.6",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROMKu8mMzWbE08Hgh_FVX0GUn07mZa_PMo2YLJ4lPXq5146DoU",
        releaseDate: "2023",
        genre: "Documentary, Biography, Drama",
    },
    {
        title: "What Is a Woman?",
        desc: "Political commentator Matt Walsh explores the changing concepts of sex and gender in the digital age, particularly the transgender rights movement, anti-transgender bigotry, and what it means to be a woman.",
        ratings: "8.2",
        status: "Available",
        image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSMnMLOYARaIAuDNAejIcbXu3bWNcUyWKj87Pvh1XLooioIiRro",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Porn to Be Free",
        desc: "Porno & libertà is a film documentary about the generation who fought against puritanism and censorship to defend freedom of speech and sexual freedom.",
        ratings: "6.1",
        status: "Available",
        image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRqK3_nPn_8UHFtyOFgDtrx1d_DfmngcZ3qbTLHZq7vbIrrllSx",
        releaseDate: "2016",
        genre: "Documentary",
    },
    {
        title: "Hotel Coolgardie",
        desc: "On a dusty highway between Australia's most isolated city and its largest gold pit lies Coolgardie - where the arrival every three months of a new pair of foreign backpackers to work the the only bar in town is a keenly anticipated event.",
        ratings: "6.8",
        status: "Available",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJBV2esPQkoh5xfRbSarswF9A36Num5iyEbnuk6DuP3CYgvM_L",
        releaseDate: "2016",
        genre: "Documentary",
    },
    {
        title: "The Darkness within La Luz del Mundo",
        desc: "In this gut-wrenching documentary, survivors share their stories of how they were abused by three generations of La Luz del Mundo church leaders.",
        ratings: "7.0",
        status: "Available",
        image: "https://www.movienewsletters.net/photos/140326R1.jpg",
        releaseDate: "2023",
        genre: "Documentary, Crime",
    },
    {
        title: "Rosa Peral's Tapes",
        desc: "This true-crime documentary film features Rosa Peral's first interview from prison since she was convicted of murdering her partner aided by an ex-lover.",
        ratings: "5.3",
        status: "Available",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRPunAXQI8_X7p1MYVmiRF-hSOinkCiCqca8p9_0vB22qS2ttjx",
        releaseDate: "2023",
        genre: "Documentary, Crime",
    },
    {
        title: "The Devil on Trial",
        desc: "Using reenactments and home videos, this dark documentary investigates the apparent possession of a young boy and the brutal murder that followed.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRBkxgl2A2PhE_6tklFLT0bxn5NLhvhsnpXGhmXBt_zotrlVHmo",
        releaseDate: "2023",
        genre: "Documentary, Crime, Horror",
    },
    {
        title: "20 Days in Mariupol",
        desc: "As the Russian invasion begins, a team of Ukrainian journalists trapped in the besieged city of Mariupol struggle to continue their work documenting the war's atrocities.",
        ratings: "8.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/John.Wick.Chapter.4.2023.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Monster Inside: America's Most Extreme Haunted House",
        desc: "Follows the story of Russ McKamey. The Navy Veteran turned master of horror, who lures horror enthusiasts into his web.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://fzmovies.net/imdb_images/Avengers.Endgame.2019.jpg",
        releaseDate: "2023",
        genre: "Documentary, Crime, Horror",
    },
    {
        title: "Koyaanisqatsi",
        desc: "A collection of expertly photographed phenomena with no conventional plot. The footage focuses on nature, humanity, and the relationship between them.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Fast.X.2023.jpg",
        releaseDate: "1982",
        genre: "Documentary, Music",
    },
    {
        title: "Deep Rising",
        desc: "The fate of the planet's last untouched wilderness, the deep ocean, is under threat as a secretive organization is about to allow massive extraction of seabed metals to address the world's energy crisis.",
        ratings: "7.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Heart.of.Stone.2023.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Dear Child",
        desc: "Set in a rehabilitation centre on the edge of the jungle, Dear Child follows a group of kids who have been rescued from the drug war, as they learn to become children again and not soldiers or drug addicts.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Dark.Knight.2008.jpg",
        releaseDate: "2020",
        genre: "Documentary",
    },
    {
        title: "Grizzly Man",
        desc: "A devastating and heart-rending take on grizzly bear activists Timothy Treadwell and Amie Huguenard, who were killed in October of 2003 while living among grizzly bears in Alaska.",
        ratings: "7.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Guy.Ritchies.the.Covenant.2023.jpg",
        releaseDate: "2005",
        genre: "Documentary, Biography",
    },
    {
        title: "Jackass Forever",
        desc: "After 11 years, the Jackass crew is back for another crusade.",
        ratings: "6.8",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Hypnotic.2023.jpg",
        releaseDate: "2022",
        genre: "Documentary, Action, Comedy",
    },
    {
        title: "Free Solo",
        desc: "Alex Honnold faces the biggest challenge of his career, climbing El Capitan in Yosemite National Park. He pursues it Free Solo which means climbing without a rope and alone.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/The%20Hunger%20Games.jpg",
        releaseDate: "2018",
        genre: "Documentary, Adventure, Sport",
    },
    {
        title: "Baraka",
        desc: "A collection of expertly photographed scenes of human life and religion.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Avatar.The.Way.of.Water.2022.jpg",
        releaseDate: "1992",
        genre: "Documentary",
    },
    {
        title: "Still: A Michael J. Fox Movie (II)",
        desc: "Follows the life of beloved actor and advocate Michael J. Fox, exploring his personal and professional triumphs and travails, and what happens when an incurable optimist confronts an incurable disease.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Equalizer.2.2018.jpg",
        releaseDate: "2023",
        genre: "Documentary, Biography",
    },
    {
        title: "Häxan",
        desc: "Fictionalized documentary showing the evolution of witchcraft, from its pagan roots to its confusion with hysteria in Eastern Europe.",
        ratings: "7.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/65.2023.jpg",
        releaseDate: "1922",
        genre: "Documentary, Fantasy, Horror",
    },
    {
        title: "Police State",
        desc: "Movie by filmmaker Dinesh D'Souza which claims federal organizations, like the FBI, CIA, and DOJ are corrupt, and are unfairly and selectively targeting Christians, conservatives, and republicans.",
        ratings: "8.0",
        status: "Unavailable",
        image: "https://fzmovies.host/imdb_images/Dredd.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "The Last Waltz",
        desc: "A film account and presentation of the final concert of The Band.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Dune.2021.jpg",
        releaseDate: "1978",
        genre: "Documentary, Biography, Music"
    },
    {
        title: "Faces of Death",
        desc: "A collection of death scenes, ranging from TV material to homemade super 8 movies.",
        ratings: "4.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Transformers.Rise.of.the.Beasts.2023.jpg",
        releaseDate: "1978",
        genre: "Documentary, Horror",
    },
    {
        title: "Moment of Contact",
        desc: "Is an exploration of extraterrestrial encounters centered on a series of events in 1996 when citizens of Varginha, Brazil, reported seeing a UFO crash and one or more strange creatures.",
        ratings: "7.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Inception.jpg",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Sticky: A (Self) Love Story",
        desc: "'Sticky' is everything your mother was too embarrassed to tell you about masturbation, in one stimulating documentary.",
        ratings: "6.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Everything.Everywhere.All.at.Once.2022.jpg",
        releaseDate: "2016",
        genre: "Documentary, Comedy",
    },
    {
        title: "Skin: A History of Nudity in the Movies",
        desc: "The definitive documentary on the history of nudity in feature films, from the early silent days to the present, studying the changes in morality that led to the use of nudity in films, while emphasizing the political, sociological, and artistic changes that shaped that history.",
        ratings: "6.7",
        status: "Available",
        image: "https://fzmovies.net/imdb_images/Spider.Man.No.Way.Home.2021.jpg",
        releaseDate: "2020",
        genre: "Documentary, History",
    },
    {
        title: "Alien Endgame",
        desc: "It follows former members of the U.S. military as they break their silence about the massive cover-up of their terrifying UFO close encounters.",
        ratings: "5.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Top.Gun.Maverick.2022.jpg",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Inside Job",
        desc: "Takes a closer look at what brought about the 2008 financial meltdown.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Jurassic%20Park.jpg",
        releaseDate: "2010",
        genre: "Documentary, Crime",
    },
    {
        title: "Carlos",
        desc: "Follows Santana's journey from 14-year-old street musician to a 10-time Grammy winning global sensation. Features unseen archival footage and tracks.",
        ratings: "8.2",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Matrix.Resurrections.2021.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Samsara (I)",
        desc: "Filmed over nearly five years in twenty-five countries on five continents, and shot on seventy-millimetre film, Samsara transports us to the varied worlds of sacred grounds, disaster zones, industrial complexes, and natural wonders.",
        ratings: "8.4",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Aquaman.2018.jpg",
        releaseDate: "2011",
        genre: "Documentary, Music",
    },
    {
        title: "Grey Gardens",
        desc: "Meet a mother and daughter, high-society dropouts, reclusive cousins of Jackie O., managing to thrive together amid the decay and disorder of their East Hampton, NY, mansion, making for an eerily ramshackle echo of the American Camelot.",
        ratings: "7.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Misanthrope.2023.jpg",
        releaseDate: "1975",
        genre: "Documentary, Comedy, Drama",
    },
    {
        title: "The Social Dilemma",
        desc: "Explores the dangerous human impact of social networking; tech experts sound the alarm on their own creations.",
        ratings: "7.6",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The%20Lord%20of%20the%20Rings%20%20The%20Fellowship%20of%20the%20Ring.jpg",
        releaseDate: "2020",
        genre: "Documentary, Drama",
    },
    {
        title: "My Octopus Teacher",
        desc: "A filmmaker forges an unusual friendship with an octopus living in a South African kelp forest, learning as the animal shares the mysteries of her world.",
        ratings: "8.1",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Tenet.2020.jpg",
        releaseDate: "2020",
        genre: "Documentary",
    },
    {
        title: "Stylebender",
        desc: "It follows a boy fighting to become the man he was destined to be. Will he find something to fight for, or will he become what he hates the most?",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Bullet.Train.2022.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
    {
        title: "Tickled",
        desc: "Journalist David Farrier stumbles upon a mysterious tickling competition online. As he delves deeper he comes up against fierce resistance, but that doesn't stop him getting to the bottom of a story stranger than fiction.",
        ratings: "7.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Gladiator.jpg",
        releaseDate: "2016",
        genre: "Documentary, Crime, Mystery",
    },
    {
        title: "David Beckham: Infamous",
        desc: "David Beckham, a household name, footballing icon and at one point the most hated man in England. A comprehensive look at David Beckham's footballing career focusing on his England redemption, World Cup dreams, trial by media and becoming brand Becks.",
        ratings: "4.7",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Mad.Max.Fury.Road.2015.jpg",
        releaseDate: "2022",
        genre: "Documentary, Biography, Sport",
    },
    {
        title: "Dear Zachary: A Letter to a Son About His Father",
        desc: "A filmmaker decides to memorialize a murdered friend when his friend's ex-girlfriend announces she is expecting his son.",
        ratings: "8.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/The.Meg.2018.jpg",
        releaseDate: "2008",
        genre: "Documentary, Biography, Crime",
    },
    {
        title: "All the Beauty and the Bloodshed",
        desc: "Follows the life of artist Nan Goldin and the downfall of the Sackler family, the pharmaceutical dynasty who was greatly responsible for the opioid epidemic's unfathomable death toll.",
        ratings: "7.5",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Heat.jpg",
        releaseDate: "2022",
        genre: "Documentary",
    },
    {
        title: "Smoke Sauna Sisterhood",
        desc: "In the darkness of a smoke sauna, women share their innermost secrets and intimate experiences, washing off the shame trapped in their bodies and regaining their strength through a sense of communion.",
        ratings: "8.0",
        status: "Available",
        image: "https://fzmovies.host/imdb_images/Blade.Runner.2049.2017.jpg",
        releaseDate: "2023",
        genre: "Documentary",
    },
]